### ISSUE TITLE
Sugestão de feature!

### ISSUE THREAD

**Issue by marcuth** [fredgrub/SWFUtils#1]
Cara gostei muito da iniciativa, estou a um bom tempo procurando uma biblioteca que permite fazer coisas com arquivos flash, mas o que eu procuro é descompilar o arquivo, extrair o que tem dentro dele, como imagens, sons e outras coisas do tipo, como o JPEXS Free Flash Decompiler faz, mas que pode ser usado no Python, porém não sei implementar isso, então fica apenas como uma sugestão. Obrigado :)

**Comment by firilisinof** [comment]
Oi @1Marcuth. Aqui, SWF, significa Standard Workload Format que é um formato para logs de supercomputadores.

Desconheço esse tipo de ferramenta, mas talvez você possa procurar por algo no repositório de pacotes do Python, o PyPI. Aqui está o link https://pypi.org/.

Abraço!
